teamspeak:
  image: viljaste/teamspeak:latest
  hostname: teamspeak
  restart: always
  ports:
    - "9987:9987/udp"
    - "30033:30033"
    - "10011:10011"
  volumes_from:
    - teamspeakdata
teamspeakdata:
  image: viljaste/data:latest
  hostname: teamspeakdata
  volumes:
    - /teamspeak
